spring:
  datasource:
    url: jdbc:h2:mem:amplis
    username: felipe
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

    # criar uma variável de ambiente em: edit configurations > variável de ambiente > clicar em + > preencher :nome=SPRING_PROFILES_ACTIVE valor=dev
    # acessar localhost:8080/h2-console
    # acessar localhost:8080/swagger-ui/index.html